import type { LegacyTaskList } from "@/src/lib/scheduling/browser-reset-store";

export function createSeedLegacyTaskLists(nowIso: string): LegacyTaskList[] {
  return [
    {
      id: 1,
      title: "Daglige rutiner",
      description: "Standard daglige oppgaver for drift",
      color: "red",
      resetEnabled: true,
      frequency: "daily",
      resetTime: "06:00",
      resetDayOfWeek: 1,
      resetDayOfMonth: 1,
      timezone: "Europe/Oslo",
      currentPeriodStartAt: undefined,
      currentPeriodEndAt: undefined,
      lastArchivedAt: undefined,
      nextResetAt: undefined,
      metadata: {
        origin: "seeded",
        sourceTemplateId: "corp.daily-routines.v1",
        createdBy: "system",
      },
      createdAt: nowIso,
      updatedAt: nowIso,
      tasks: [
        {
          id: 1,
          title: "Sjekk åpning og klargjøring",
          description: "Bekreft at stasjonene er klare før oppstart.",
          completed: false,
          metadata: {
            origin: "seeded",
            sourceTemplateId: "corp.daily-routines.v1.task.1",
            createdBy: "system",
          },
          createdAt: nowIso,
          updatedAt: nowIso,
        },
        {
          id: 2,
          title: "Kontroller råvarestatus",
          description: "Kontroller beholdning, datoer og avvik.",
          completed: false,
          metadata: {
            origin: "seeded",
            sourceTemplateId: "corp.daily-routines.v1.task.2",
            createdBy: "system",
          },
          createdAt: nowIso,
          updatedAt: nowIso,
        },
      ],
    },
    {
      id: 2,
      title: "Ukentlig kontroll",
      description: "Standard ukentlige kontrolloppgaver",
      color: "blue",
      resetEnabled: true,
      frequency: "weekly",
      resetTime: "06:00",
      resetDayOfWeek: 1,
      resetDayOfMonth: 1,
      timezone: "Europe/Oslo",
      currentPeriodStartAt: undefined,
      currentPeriodEndAt: undefined,
      lastArchivedAt: undefined,
      nextResetAt: undefined,
      metadata: {
        origin: "seeded",
        sourceTemplateId: "corp.weekly-control.v1",
        createdBy: "system",
      },
      createdAt: nowIso,
      updatedAt: nowIso,
      tasks: [
        {
          id: 1,
          title: "Utfør renholdsrunde",
          description: "Kontroller og dokumenter ukentlig renhold.",
          completed: false,
          metadata: {
            origin: "seeded",
            sourceTemplateId: "corp.weekly-control.v1.task.1",
            createdBy: "system",
          },
          createdAt: nowIso,
          updatedAt: nowIso,
        },
        {
          id: 2,
          title: "Sjekk HMS-punkter",
          description: "Verifiser avvik, tiltak og signatur.",
          completed: false,
          metadata: {
            origin: "seeded",
            sourceTemplateId: "corp.weekly-control.v1.task.2",
            createdBy: "system",
          },
          createdAt: nowIso,
          updatedAt: nowIso,
        },
      ],
    },
  ].map((list) => ({
    ...list,
    tasks: list.tasks.map((task) => ({ ...task })),
    metadata: {
      ...list.metadata,
      createdBy: list.metadata?.createdBy ?? "system",
    },
    currentPeriodStartAt: list.currentPeriodStartAt,
    currentPeriodEndAt: list.currentPeriodEndAt,
    lastArchivedAt: list.lastArchivedAt,
    nextResetAt: list.nextResetAt,
  }));
}
